=== Exabyte-io/esse/schema/method_units/physical/rmm_diis.json
{
    "schemaId": "method-derived-qm-rmm-diis",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Residual minimization method using direct inversion of the iterative subspace (RMM-DIIS) schema",
    "description": "Relevant publications: 10.1016/0009-2614(80)80396-4, 10.1088/0305-4470/18/9/018",
    "allOf": [
        {
            "$ref": "../unit_base_physical.json"
        }
    ],
    "properties": {
        "mathematicalMethodsCategoryPaths": {
            "type": "array",
            "items": {
                "anyOf": [
                    {
                        "enum": [
                            "opt/diff/order1/sd"
                        ]
                    },
                    {
                        "enum": [
                            "linalg/ortho/gs"
                        ]
                    }
                ]
            }
        },
        "modelCategoryPaths": {
            "type": "array",
            "items": {
                "anyOf": [
                    {
                        "enum": [
                            "pb/qm/*"
                        ]
                    }
                ]
            }
        },
        "type": {
            "enum": [
                {
                    "name": "RMM-DIIS eigensolver",
                    "slug": "rmm-diis"
                }
            ]
        },
        "parameters": {
            "type": "object",
            "properties": {
                "blockSize": {
                    "description": "Number of eigenvalues to be solved simultaneously (blocked mode)",
                    "$ref": "../../core/reusable/parameters/int.json"
                },
                "diis.maximumSteps": {
                    "description": "Maximum number of iterative steps",
                    "$ref": "../../core/reusable/parameters/int.json"
                },
                "orthonormalization.nDimensions": {
                    "description": "Dimension of Orthonormalization procedure (usually Gram-Schmidt)",
                    "$ref": "../../core/reusable/parameters/int.json"
                },
                "convergence": {
                    "description": "Convergence criterion",
                    "$ref": "../../core/reusable/parameters/number.json"
                }
            }
        }
    }
}

=== Exabyte-io/esse/example/method_units/physical/rmm_diis.json
{
    "mathematicalMethodsCategoryPaths": [
        "opt/diff/order1/sd",
        "linalg/ortho/gs"
    ],
    "modelCategoryPaths": [
        "pb/qm/*"
    ],
    "type": {
        "name": "RMM-DIIS eigensolver",
        "slug": "rmm-diis"
    },
    "parameters": {
        "blockSize": {
            "value": 4
        },
        "diis.maximumSteps": {
            "value": 6
        },
        "orthonormalization.nDimensions": {
            "value": 16
        },
        "convergence": {
            "value": 1e-3,
            "precision": true
        }
    }
}
