=== Exabyte-io/esse/schema/new_model.json
{
    "schemaId": "new-model",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "model schema (base)",
    "properties": {
        "name": {
            "type": "string"
        },
        "path": {
            "$ref": "core/reusable/category_path.json"
        },
        "categories": {
            "description": "Model categories",
            "$ref": "core/reusable/categories.json"
        },
        "parameters": {
            "type": "object",
            "description": "Model parameters defined in-place or via model mixins"
        },
        "method": {
            "$ref": "method.json"
        },
        "reference": {
            "$ref": "core/reference/literature.json"
        },
        "tags": {
            "$ref": "core/primitive/array_of_strings.json"
        }
    },
    "required": [
        "categories",
        "parameters",
        "method"
    ]
}

=== Exabyte-io/esse/example/model/categorized_model.json
{
    "name": "PZ+U (magnetism)",
    "categories": {
        "tier1": {
            "name": "physics-based",
            "slug": "pb"
        },
        "tier2": {
            "name": "quantum-mechanical",
            "slug": "qm"
        },
        "tier3": {
            "name": "density functional theory",
            "slug": "dft"
        },
        "type": {
            "name": "Kohn-Sham DFT",
            "slug": "ksdft"
        },
        "subtype": {
            "name": "Local Density Approximation",
            "slug": "lda"
        }
    },
    "parameters": {
        "functional": "pz",
        "spinPolarization": "collinear",
        "hubbardType": "U"
    },
    "method": {
        "...": "include(../method/categorized_method.json)"
    }
}
